'use client';

import { useState } from 'react';
import { Button } from '@/components/ui/Button';

export function CopyDiscordButton({ guildName, matchingUrl, simulatorUrl }: {
  guildName: string;
  matchingUrl: string | null;
  simulatorUrl: string | null;
}) {
  const [copied, setCopied] = useState(false);

  const handleCopy = async () => {
    const links = [
      matchingUrl ? `🎯 **Matching Board**: ${matchingUrl}` : null,
      simulatorUrl ? `🎮 **Simulator**: ${simulatorUrl}` : null,
    ].filter(Boolean).join('\n');

    const text = `📋 **${guildName} - SWGOH Tools**\n\n${links}\n\n_Generated by SWGOH Manager_`;

    try {
      await navigator.clipboard.writeText(text);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch (err) {
      console.error('Failed to copy:', err);
    }
  };

  return (
    <Button
      variant="secondary"
      onClick={handleCopy}
      disabled={!matchingUrl && !simulatorUrl}
    >
      {copied ? '✓ Copied!' : '📋 Copy for Discord'}
    </Button>
  );
}